export {default as USERS} from './images/users-svgrepo-com.svg';
export {default as HOUSE} from './images/home-svgrepo-com.svg';
export {default as LOCATION} from './images/location-svgrepo-com.svg'
export {default as CALENDAR} from './images/calendar-minimalistic-svgrepo-com.svg'
export {default as PORTFOLIO} from './images/portfolio.jpg'
export {default as INTERIOR} from './images/interior.jpg'
export {default as INVESTMENT} from './images/investment.jpg'
export {default as LEGAL} from './images/legal.jpg'
export {default as PHONE} from './images/phone-svgrepo-com.svg'
export {default as EMAIL} from './images/email-svgrepo-com.svg'